

import './globals.css';
// import Header from '../component/Header';
import Header from './Header';
import SideBar from '../component/SideBar';
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header>
          <Header />
        </header>
        <div className='flex'>
          <aside className='w-[30%] bg-red-300 h-screen overflow-scroll'>
          <SideBar />
        </aside>
        <main className='w-[70%] bg-slate-300'>{children}</main>
        </div>
      </body>
    </html>
  );
}

