// 'use client'
import './globals.css';
import SideBar from './components/SideBar';
import Header from './components/Header';
const getTodos = async () => {
  const res=await fetch('https://jsonplaceholder.typicode.com/todos')
  return res.json();
}
export default async function RootLayout({ children }) {
  const todos = await getTodos();
  console.log(todos)
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header>
          <Header />
        </header>
        <div className='flex'>
          <aside className='w-[20%] h-screen overflow-scroll'>
            {/* {todos.map((todo) => (
              <SideBar
                key={todo.id}
                id={todo.id}
              />
          ))} */}
            <SideBar todos={ todos} />
        </aside>
        <main className='w-[80%] bg-slate-300'>{children}</main>
        </div>
      </body>
    </html>
  );
}

